/*
**  ErrorMsg.h
**  error message functions.
**
**  Jack, 2002.5.9.
*/
#ifndef _ERRORMSG_H_
#define _ERRORMSG_H_


// DEFINE //////////////////////////////////////////////////////////////////////////////////////////////////////////
//#define DEBUG_MSG           //陪ボ代刚癟

#define BIG5_VERSION        //羉砰╰参
//#define GB_VERSION          //虏砰╰参

//
//-----------------------------------------------------------------------------------------------
#ifdef  BIG5_VERSION    //{
//#define     GAME_FONT_NAME                                  "地眃ぶゅW3"
#define     GAME_FONT_NAME                                  ""

#define     ERRMSG_WINSOCKET_VERSION                        "Winsocket Version Error!!"
#define     ERRMSG_INIT_SOCKET                              "Init Socket Error!!"
#define     ERRMSG_CANT_ASYNC                               "Can't Async!!"
#define     ERRMSG_CANT_CONNECTED                           "礚猭硈钡狝竟叫祔刚"
#define     ERRMSG_MUST_INPUT_ACCOUNT                       "叫块眀腹"
#define     ERRMSG_MUST_INPUT_PASSWORD                      "叫块盞絏"
#define     ERRMSG_MUST_INPUT_NEW_PASSWORD                  "叫块穝盞絏"
#define     ERRMSG_MUST_INPUT_VERIFY_PASSWORD               "叫絋粄逆いΩ块盞絏"
#define     ERRMSG_MUST_CONFIRM_PASSWORD                    "叫絋玂ㄢΩ块盞絏璓"
#define     ERRMSG_CHANGE_PASSWORD_OK                       "э盞絏Θ"
#define     ERRMSG_DOOR_SERVER_CLOSED                       "芔狝竟闽超"
#define     ERRMSG_ZONE_SERVER_CLOSED                       "跋办狝竟闽超"
#define     ERRMSG_DOOR_KICKED                              "祅砆┶荡"
#define     ERRMSG_ACCOUNT_IDUSED                           "眀腹嘿竒砆ㄏノ"
#define     ERRMSG_LOGIN_DOOR_SERVER_FAILED                 "祅芔狝竟ア毖"
#define     ERRMSG_LOGIN_DOOR_SERVER_ID_ERROR               "祅嘿ぃ"
#define     ERRMSG_LOGIN_DOOR_SERVER_PASSWORD_ERROR         "盞絏岿粇"
#define     ERRMSG_LOGIN_DOOR_SERVER_ID_DENIED              "祅砆┶荡"
#define     ERRMSG_LOGIN_REPEAT                             "祅狡叫㎝⒄③羛么"
#define     ERRMSG_LOGIN_WORLD_SERVER_FAILED                "祅狝竟ア毖"
#define		ERRMSG_WORLD_LOGIN_ERRORID						"祅狝竟眀腹岿粇"
#define		ERRMSG_WORLD_LOGIN_ERRORPW						"祅狝竟盞絏岿粇"
#define		ERRMSG_WORLD_LOGIN_DENIED						"祅狝竟砆┶荡"
#define		ERRMSG_WORLD_LOGIN_KICKED						"砆狝竟金"
#define		ERRMSG_WORLD_LOGIN_REPEAT						"狡祅狝竟"
#define		ERRMSG_ZONE_LOGIN_ERRORID						"祅跋办狝竟眀腹岿粇"
#define		ERRMSG_ZONE_LOGIN_ERRORPW						"祅跋办狝竟盞絏岿粇"
#define		ERRMSG_ZONE_LOGIN_DENIED						"祅跋办狝竟砆┶荡"
#define		ERRMSG_ZONE_LOGIN_KICKED						"砆跋办狝竟矗"
#define     ERRMSG_CHARACTER_NAME_USED                      "à︹嘿竒砆ㄏノ"
#define     ERRMSG_CREATE_CHARACTER_FAILED                  "承à︹ア毖"
#define     ERRMSG_DELETE_CHARACTER_FAILED                  "埃à︹ア毖"
#define     ERRMSG_LOGIN_ZONE_SERVER_FAILED                 "祅跋办狝竟ア毖"
#define		ERRMSG_ZONE_LOGIN_REPEAT						"╰参浪代Τㄏノ眤眀腹祅"
#define     ERRMSG_VERSION_ERROR                            "セ岿粇叫穝程穝セ"
#define		ERRMSG_ERROR_DATA								"戈岿粇"
#define     ERRMSG_CANT_LOGIN_ZONE_SERVER                   "ぃ祅跋办狝竟"
#define     ERRMSG_CANT_GET_ZONE_SERVER_ADDRESS             "ぃ莉眔跋办狝竟"
#define		ERRMSG_PLEASE_INPUT_MAINNAME					"叫块à︹嘿"
//
//text messages
#define     TEXTMSG_PLEASE_INSERT_CDROM             "叫础材眎盒"
#define     TEXTMSG_WINDOW_NAME                     "ぇ贾彻"
#define     TEXTMSG_GAME_VERSION                    "ぇ贾彻"  //
//
#define     TEXTMSG_JOIN_GAME_OK                    "笴栏Θ"
#define     TEXTMSG_JOIN_GAME_ERROR_NAME_DUPLICATE  "笴栏ア毖竒"
#define     TEXTMSG_JOIN_GAME_ERROR_PLAYER_FULL     "笴栏ア毖硂竒甧ぃ"
#define     TEXTMSG_DISCONNECT_WITH_SERVER          "眤籔狝叭竟硈絬耞秨"
#define     TEXTMSG_WAIT_FOR_LOADING                "タ更戈い叫单..."
#define     TEXTMSG_CREATE_PLAYER                   "%s 笴栏"
#define     TEXTMSG_DESTROY_PLAYER                  "%s 瞒秨笴栏"
#define     TEXTMSG_WELCOME_JOIN                    "舧ㄓ硂"
#define     TEXTMSG_WAIT_FOR_TRANSFER               "叫单..."
//
#define     TEXTMSG_NAME_ITEM                       "笵ㄣ"
#define     TEXTMSG_NAME_MAGIC                      "м"
#define     TEXTMSG_NAME_RACE                       "贺壁"
#define     TEXTMSG_NAME_COUNTRY                    "瓣產"
#define     TEXTMSG_NAME_ORGANIZE                   "舱麓"
#define     TEXTMSG_NAME_TITLE                      "繷晃"
#define     TEXTMSG_NAME_SEX                        "┦"
#define     TEXTMSG_NAME_HP                         "ネ㏑"
#define     TEXTMSG_NAME_MP                         "ず"
#define     TEXTMSG_NAME_ATT                        "ю阑"
#define     TEXTMSG_NAME_DP                         "ň縨"
#define     TEXTMSG_NAME_XFIRE                      "╰ň縨玒计"
#define     TEXTMSG_NAME_XWATER                     "╰ň縨玒计"
#define     TEXTMSG_NAME_XDUST                      "╰ň縨玒计"
#define     TEXTMSG_NAME_XAIR                       "ň縨玒计"
#define     TEXTMSG_NAME_DEXT                       "庇倍"
#define     TEXTMSG_NAME_MOVE_SPEED                 "簿笆硉"
#define     TEXTMSG_NAME_EYESHOT                    "跌偿畖"
#define     TEXTMSG_NAME_WIT                        "醇"
#define     TEXTMSG_NAME_STRENGTH                   "秖"
#define     TEXTMSG_NAME_RESP                       "は莱"
#define     TEXTMSG_NAME_VIM                        ""
#define     TEXTMSG_NAME_SPIRIT                     "弘"
#define     TEXTMSG_NAME_EXP                        "竒喷"
#define     TEXTMSG_NAME_LEVEL                      "单"
#define     TEXTMSG_NAME_SHIPSPEED                  "硉"
#define     TEXTMSG_NAME_WINDDIR                    ""
#define     TEXTMSG_NAME_WEATHER                    "ぱ"
//
#define     TEXTMSG_NOT_ENOUGH_BAG_SPACE            "⊿Τì镑丁"
#define     TEXTMSG_NOT_ENOUGH_MAP_SPACE            "竒甧ぃ穝狥﹁"
#define     TEXTMSG_NOT_ENOUGH_MONEY                "⊿Τì镑窥"
#define     TEXTMSG_NOT_ENOUGH_MP                   "⊿Τì镑猭"
#define     TEXTMSG_CAN_NOT_USE_MAGIC_IN_TOWN       "м马ńぃㄏノ"
#define     TEXTMSG_LEVEL_UPGRADE                   "单ど蔼"
//
#define     TEXTMSG_ABNORMITY_FUNK                  "倪"
#define     TEXTMSG_ABNORMITY_FRENZY                "╣忌"
#define     TEXTMSG_ABNORMITY_WEEK                  "店畓"
#define     TEXTMSG_ABNORMITY_CRAZY                 "浩╣"
#define     TEXTMSG_ABNORMITY_ANGRY                 "极"
#define     TEXTMSG_ABNORMITY_VIRUS                 "い瑀"
#define     TEXTMSG_ABNORMITY_NUMB                  "陈肤"
#define     TEXTMSG_ABNORMITY_COSTIVE               "搭硉"
#define     TEXTMSG_ABNORMITY_NIMBLE                "硉"
//
#define     TEXTMSG_ADD_STATUS                      "ㄏ瞷钵盽"
#define     TEXTMSG_DEL_STATUS                      "秆埃钵盽"
//
#define     TEXTMSG_BUY_COST                        "禦基"
#define     TEXTMSG_SELL_VALUE                      "芥基"
#define     TEXTMSG_ADD_STRENGTH                    "秖"
#define     TEXTMSG_ADD_RESP                        "は莱"
#define     TEXTMSG_ADD_VIM                         ""
#define     TEXTMSG_ADD_SPIR                        "弘"
#define     TEXTMSG_ADD_HP                          "ネ㏑"
#define     TEXTMSG_ADD_MAX_HP                      "程ネ㏑"
#define     TEXTMSG_ADD_MP                          "猭"
#define     TEXTMSG_ADD_MAX_MP                      "程猭"
#define     TEXTMSG_ADD_ATT                         "ю阑"
#define     TEXTMSG_ADD_DP                          "ň縨"
#define     TEXTMSG_ADD_XFIRE                       "╰ň縨玒计"
#define     TEXTMSG_ADD_XWATER                      "╰ň縨玒计"
#define     TEXTMSG_ADD_XDUST                       "╰ň縨玒计"
#define     TEXTMSG_ADD_XAIR                        "╰ň縨玒计"
#define     TEXTMSG_ADD_DEXT                        "庇倍"
#define     TEXTMSG_ADD_WIT                         "醇"
#define     TEXTMSG_ADD_ATTACK_SPEED                "ю阑硉"
#define     TEXTMSG_ADD_MOVE_SPEED                  "簿笆硉"
#define     TEXTMSG_ADD_EYESHOT                     "跌偿畖"
#define     TEXTMSG_ADD_HP_RESTORE                  "ネ㏑確硉"
#define     TEXTMSG_ADD_MP_RESTORE                  "ず確硉"
//
#define     TEXTMSG_YOU_ENDED_ALLY_WITH_OTHER       "眤沧ゎ㎝~C4%s~C0羛幅"
#define     TEXTMSG_OTHER_ENDED_ALLY_WITH_YOU       "~C4%s~C0沧ゎ㎝眤羛幅"
#define     TEXTMSG_YOU_CANCELED_ALLY_REQUEST       "眤辨㎝~C4%s~C0羛幅叫―"
#define     TEXTMSG_OTHER_CANCLED_ALLY_REQUEST      "~C4%s~C0辨㎝眤羛幅叫―"
#define     TEXTMSG_YOU_HAVE_ALLIED_WITH_OTHER      "眤竒Θ㎝~C4%s~C0羛幅"
#define     TEXTMSG_HAVE_SEND_ALLY_REQUEST          "竒~C4%s~C0祇羛幅叫―叫单滦"
#define     TEXTMSG_HAVE_RECEIVED_ALLY_REQUEST      "~C4%s~C0眤祇羛幅叫―"
#define     TEXTMSG_NEUTRAL_WITH_OTHER              "眤瞷㎝~C4%s~C0玂いミ"
#define     TEXTMSG_NEUTRAL_WITH_YOU                "~C4%s~C0瞷㎝眤玂いミ"
#define     TEXTMSG_OPPOSE_WITH_OTHER               "眤瞷㎝~C4%s~C0琌寄癸"
#define     TEXTMSG_OPPOSE_WITH_YOU                 "~C4%s~C0瞷㎝眤琌寄癸"
//
#define     TEXTMSG_HAVE_RECEIVED_TASK              "钡穝ヴ叭"
#define     TEXTMSG_HAVE_FINISHED_TASK              "ヴ叭ЧΘ"
#define     TEXTMSG_HAVE_CANCELED_TASK              "ヴ叭"
//
#define     TEXTMSG_SOMEONE_IS_BUSY                 "%s タΓ帝㎡"
//
#define     TEXTMSG_GET_EXP                         "莉眔竒喷 %d"
#define     TEXTMSG_GET_MONEY                       "莉眔刽 %d"
#define     TEXTMSG_GET_SKILL_POINT                 "莉眔м砃翴 %d"
#define     TEXTMSG_GET_SOMETHING                   "莉眔 %s"
#define     TEXTMSG_USE_SOMETHING                   "ㄏノ珇 %s"
#define     TEXTMSG_USE_MONEY                       "ㄏノ刽 %d"
#define     TEXTMSG_JOIN_ORGANIZE                   "眤 %s"
#define     TEXTMSG_SECEDE_ORGANIZE                 "眤癶 %s"
//
#define     TEXTMSG_ENUM_PLAYER_KILL_NPC            "%s 炳┣ %d "
#define     TEXTMSG_ENUM_PLAYER_CRYSTAL             "%s 局Τ垂 %d 聋"
#define     TEXTMSG_ENUM_PLAYER_WHERE               "%s 瞷矪 %s  %s"
#define     TEXTMSG_ENUM_PLAYER_LEVEL               "%s 瞷单琌 %d"
#define     TEXTMSG_ENUM_PLAYER_CASH                "%s 瞷局Τ窥 %d"
#define     TEXTMSG_ENUM_RELATION_ALLY              "%s 籔 %s 闽玒琌羛幅"
#define     TEXTMSG_ENUM_RELATION_OPPOSE            "%s 籔 %s 闽玒琌寄癸"
#define     TEXTMSG_ENUM_RELATION_NEUTRAL           "%s 籔 %s 闽玒琌いミ"
#define     TEXTMSG_ENUM_PLAYER_NAME                "產 %s"
#define     TEXTMSG_ONLY_YOU_IN_THE_WORLD           "ヘ玡硂Τ產 %s"
//
#define     TEXTMSG_ASK_SURE_DELETE_CHAR            "眤絋﹚惠璶埃%s盾"
#define     TEXTMSG_YES_DELETE_CHAR                 "埃"
#define     TEXTMSG_NO_DELETE_CHAR                  ""
#define     TEXTMSG_EXIST_SAME_NAME_SAVE_CHAR       "竒叫穝㏑"
//
#define     TEXTMSG_MENU_MINIMIZE                   "程て"
#define     TEXTMSG_MENU_MINIMIZE_INFO              "~C0程て~C0"
#define     TEXTMSG_MENU_MAXIMIZE                   "程て"
#define     TEXTMSG_MENU_MAXIMIZE_INFO              "~C0程て~C0"
#define     TEXTMSG_MENU_CLOSE                      "闽超"
#define     TEXTMSG_MENU_CLOSE_INFO                 "~C0闽超~C0"
//
#define     TEXTMSG_MENU_STATE                      "篈(C)"
#define     TEXTMSG_MENU_STATE_INFO                 "~C0篈(~C4C~C0)~C0"
#define     TEXTMSG_MENU_ITEM                       "杆称(I)"
#define     TEXTMSG_MENU_ITEM_INFO                  "~C0杆称(~C4I~C0)~C0"
#define     TEXTMSG_MENU_MAGIC                      "м(T)"
#define     TEXTMSG_MENU_MAGIC_INFO                 "~C0м(~C4T~C0)~C0"
#define     TEXTMSG_MENU_TASK                       "ヴ叭(Q)"
#define     TEXTMSG_MENU_TASK_INFO                  "~C0ヴ叭(~C4Q~C0)~C0"
#define     TEXTMSG_MENU_SHIP                       "差唉(S)"
#define     TEXTMSG_MENU_SHIP_INFO                  "~C0差唉(~C4S~C0)~C0"
#define     TEXTMSG_MENU_HP                         "HP %d / %d"
#define     TEXTMSG_MENU_MP                         "MP %d / %d"
#define     TEXTMSG_MENU_ADDRESS_BOOK               "硄癟茂(M)"
#define     TEXTMSG_MENU_ADDRESS_BOOK_INFO          "~C0硄癟茂(~C4M~C0)~C0"
#define     TEXTMSG_MENU_CHAT_RECORD                "癸杠癘魁(H)"
#define     TEXTMSG_MENU_CHAT_RECORD_INFO           "~C0癸杠癘魁(~C4H~C0)~C0"
#define     TEXTMSG_MENU_CHAT_INPUT                 "块ゅ(Enter)"
#define     TEXTMSG_MENU_CHAT_INPUT_INFO            "~C0块ゅ(~C4Enter~C0)~C0"
//
#define     TEXTMSG_UIITEM_DROP_GOLD                "メ窥"
//
#define     TEXTMSG_INVALID_SAVE_VERSION            "郎セ岿粇"
#define     TEXTMSG_INVALID_CHECKSUM                "计沮岿粇"
//
#define     TEXTMSG_NEED_MP                         "MP:"
//
#define     TEXTMSG_UISETUP_ALLY                    "羛幅"
#define     TEXTMSG_UISETUP_OPPOSE                  "寄癸"
#define     TEXTMSG_UISETUP_CHAT_AUDIBLE            "肚癳獺"
#define     TEXTMSG_UISETUP_CHAT_FORBID             "姜獺"
//
#define     TEXTMSG_PREV_PAGE                       ""
#define     TEXTMSG_NEXT_PAGE                       ""
//
#define     TEXTMSG_ADD_BASE_STRENGTH               "糤膀セ秖"
#define     TEXTMSG_SUB_BASE_STRENGTH               "搭ぶ膀セ秖"
#define     TEXTMSG_ADD_BASE_INSTINCT               "糤膀セ谋"
#define     TEXTMSG_SUB_BASE_INSTINCT               "搭ぶ膀セ谋"
#define     TEXTMSG_ADD_BASE_WIT                    "糤膀セ醇"
#define     TEXTMSG_SUB_BASE_WIT                    "搭ぶ膀セ醇"
#define     TEXTMSG_ADD_BASE_LUCK                   "糤膀セ笲"
#define     TEXTMSG_SUB_BASE_LUCK                   "搭ぶ膀セ笲"
//
#define     TEXTMSG_CREDIT_CARD                     "獺ノ"
#define     TEXTMSG_POINTS_CARD                     "计"
#define     TEXTMSG_IME_QUANJIAO                    "à"
#define     TEXTMSG_IME_BANJIAO                     "à"
#define     TEXTMSG_IME_CHINESE_PUNCTUATION         "いゅ夹翴"
#define     TEXTMSG_IME_ENGLISH_PUNCTUATION         "璣ゅ夹翴"

#define     TEXTMSG_SERVER_ACTIVE                   "币笆"
#define     TEXTMSG_SERVER_MAINTAIN                 "蝴臔い"
#define     TEXTMSG_COUNTRY_NAME_CHINA              "い瓣"
#define     TEXTMSG_COUNTRY_NAME_ENGLAND            "璣瓣"
#define     TEXTMSG_COUNTRY_NAME_SWEDEN             "风ㄥ"
#define     TEXTMSG_COUNTRY_NAME_FRANCE             "猭瓣"
#define     TEXTMSG_COUNTRY_NAME_GERMANY            "紈瓣"
#define     TEXTMSG_COUNTRY_NAME_SPAIN              "﹁痁"
#define     TEXTMSG_COUNTRY_NAME_PORTUGAL           "覆靛"
#define     TEXTMSG_COUNTRY_NAME_ITALY              "竡"
#define     TEXTMSG_COUNTRY_NAME_DENMRKE            "う沉"
#define     TEXTMSG_COUNTRY_NAME_FINLAND            "孽"
#define     TEXTMSG_COUNTRY_NAME_GREECE             "镁"
#define     TEXTMSG_COUNTRY_NAME_NORWAY             ""
#define     TEXTMSG_COUNTRY_NAME_IRELAND            "稲焊孽"
#define     TEXTMSG_COUNTRY_NAME_TUNIS              "ェ吹"
#define     TEXTMSG_COUNTRY_NAME_ARAB               "┰"
#define     TEXTMSG_COUNTRY_NAME_TURKEY             "φㄤ"
#define     TEXTMSG_COUNTRY_NAME_AFRICA             "獶瑆"
#define     TEXTMSG_COUNTRY_NAME_KOREA              "龙瓣"
#define     TEXTMSG_COUNTRY_NAME_JAPAN              "らセ"
#define     TEXTMSG_COUNTRY_NAME_INDIA              ""
#define     TEXTMSG_COUNTRY_NAME_DUMMY              "礚"

#define     TEXTMSG_CAREER_NAME_GENERAL             "矗服"
#define     TEXTMSG_CAREER_NAME_SWORDER             "糃"
#define     TEXTMSG_CAREER_NAME_THIEF               "敖"
#define     TEXTMSG_CAREER_NAME_TRADER              "坝"
#define     TEXTMSG_CAREER_NAME_EXPLORER            "贝繧產"
#define     TEXTMSG_CAREER_NAME_CLERIC              "畍"
#define     TEXTMSG_CAREER_NAME_HOROSCOPER          "琍砃"
#define     TEXTMSG_CAREER_NAME_DUMMY               "礚"

#define     TEXTMSG_SEX_NAME_MALE                   "╧"
#define     TEXTMSG_SEX_NAME_FEMALE                 ""
#define     TEXTMSG_SEX_NAME_DUMMY                  "礚"

#define     TEXTMSG_WEATHER_TYPE_NAME_WIND          ""
#define     TEXTMSG_WEATHER_TYPE_NAME_FINE          "锤"
#define     TEXTMSG_WEATHER_TYPE_NAME_RAIN          "獴"
#define     TEXTMSG_WEATHER_TYPE_NAME_THUNDER       "筽"
#define     TEXTMSG_WEATHER_TYPE_NAME_FOG           "铭"
#define     TEXTMSG_WEATHER_TYPE_DUMMY              "??"

#define     TEXTMSG_CHAT_CHEER_GAOXING              "蔼砍"
#define     TEXTMSG_CHAT_ANGRY_QIFEN                "极"
#define     TEXTMSG_CHAT_BECKON_NIHAO               ""
#define     TEXTMSG_CHAT_BECKON_ZHAOSHOU            "┷も"
#define     TEXTMSG_CHAT_BECKON_ZAIJIAN             "ǎ"
#define     TEXTMSG_CHAT_COURT_QIUAI                "―稲"
#define     TEXTMSG_CHAT_FAINT_YUNDAO               "穡"
#define     TEXTMSG_CHAT_SAY_NO_BU                  "ぃ"
#define     TEXTMSG_CHAT_BOW_JUGONG                 "六癭"
#define     TEXTMSG_CHAT_WIN_SHENGLI                "秤"
#define     TEXTMSG_CHAT_SWASH_XIAHU                "纞颁"
#define     TEXTMSG_CHAT_XXPOWER_XULI               "籛"
#define     TEXTMSG_CHAT_XXBEATED_SHOUSHANG         "端"

#define		TEXTMSG_ASK_BUY_ITEM					"珇%s\n基%d\n眤絋﹚潦禦盾"
#define		TEXTMSG_ASK_DEL_CHARACTER				"埃%s\n眤絋﹚盾"


#define     GAMEMSG_PLAYER_JOIN                     "%s 秈ㄓ"
#define     GAMEMSG_PLAYER_EXIT                     "%s "
#define     GAMEMSG_PLAYER_FIGHT_ENABLED            "э跑驹矮家Α"
#define     GAMEMSG_PLAYER_FIGHT_DISABLED           "э跑タ盽家Α"
#define     GAMEMSG_ENTER_ZONE                      "ㄓ %s"

#define		TEXTMSG_BANK_LOAD_MONEY					"眤璶ぶ窥"
#define		TEXTMSG_BANK_SAVE_MONEY					"眤璶ぶ窥"
#endif//BIG5_VERSION }

//-----------------------------------------------------------------------------------------------
//-----------------------------------------------------------------------------------------------
#ifdef  GB_VERSION  //{
#define     GAME_FONT_NAME                                  "宋体"

#define     ERRMSG_WINSOCKET_VERSION                        "Winsocket Version Error!!"
#define     ERRMSG_INIT_SOCKET                              "Init Socket Error!!"
#define     ERRMSG_CANT_ASYNC                               "Can't Async!!"
#define     ERRMSG_CANT_CONNECTED                           "无法连接服务器，请稍后重试！"
#define     ERRMSG_MUST_INPUT_ACCOUNT                       "请输入账号！"
#define     ERRMSG_MUST_INPUT_PASSWORD                      "请输入密码！"
#define     ERRMSG_MUST_INPUT_NEW_PASSWORD                  "请输入新的密码！"
#define     ERRMSG_MUST_INPUT_VERIFY_PASSWORD               "请在确认栏中再次输入密码！"
#define     ERRMSG_MUST_CONFIRM_PASSWORD                    "请确保你两次输入的密码一致！"
#define     ERRMSG_CHANGE_PASSWORD_OK                       "修改密码成功。"
#define     ERRMSG_DOOR_SERVER_CLOSED                       "大厅服务器已关闭！"
#define     ERRMSG_ZONE_SERVER_CLOSED                       "区域服务器已关闭！"
#define     ERRMSG_DOOR_KICKED                              "登入被拒绝！"
#define     ERRMSG_ACCOUNT_IDUSED                           "账号名称已经被使用！"
#define     ERRMSG_LOGIN_DOOR_SERVER_FAILED                 "登入大厅服务器失败！"
#define     ERRMSG_LOGIN_DOOR_SERVER_ID_ERROR               "登入名称不存在！"
#define     ERRMSG_LOGIN_DOOR_SERVER_PASSWORD_ERROR         "密码错误！"
#define     ERRMSG_LOGIN_DOOR_SERVER_ID_DENIED              "登入被拒绝！"
#define     ERRMSG_LOGIN_REPEAT                             "登入重复，请和??联系！"
#define     ERRMSG_LOGIN_WORLD_SERVER_FAILED                "登入世界服务器失败！"
#define		ERRMSG_WORLD_LOGIN_ERRORID						"WORLD LOGIN ERROR ID !"
#define		ERRMSG_WORLD_LOGIN_ERRORPW						"WORLD LOGIN ERROR PASSWORD !"
#define		ERRMSG_WORLD_LOGIN_DENIED						"WORLD LOGIN DENIED !"
#define		ERRMSG_WORLD_LOGIN_KICKED						"WORLD LOGIN KICKED !"
#define		ERRMSG_WORLD_LOGIN_REPEAT						"WORLD LOGIN REPEAT !"
#define		ERRMSG_ZONE_LOGIN_ERRORID						"ZONE LOGIN ERROR ID !"
#define		ERRMSG_ZONE_LOGIN_ERRORPW						"ZONE LOGIN ERROR PASSWORD !"
#define		ERRMSG_ZONE_LOGIN_DENIED						"ZONE LOGIN DENIED !"
#define		ERRMSG_ZONE_LOGIN_KICKED						"ZONE LOGIN KICKED !"
#define     ERRMSG_CHARACTER_NAME_USED                      "角色名称已经被使用！"
#define     ERRMSG_CREATE_CHARACTER_FAILED                  "创建角色失败！"
#define     ERRMSG_DELETE_CHARACTER_FAILED                  "删除角色失败！"
#define     ERRMSG_LOGIN_ZONE_SERVER_FAILED                 "登入区域服务器失败！"
#define		ERRMSG_ZONE_LOGIN_REPEAT						"ZONE LOGIN REPEAT!"
#define     ERRMSG_VERSION_ERROR                            "版本错误，请更新最新版本！"
#define		ERRMSG_ERROR_DATA								"DATA ERROR !"
#define     ERRMSG_CANT_LOGIN_ZONE_SERVER                   "不能登入区域服务器！"
#define     ERRMSG_CANT_GET_ZONE_SERVER_ADDRESS             "不能获得区域服务器地址！"
#define		ERRMSG_PLEASE_INPUT_MAINNAME					"PLEASE INPUT CHARACTER MAINNAME !"
//
//text messages
#define     TEXTMSG_PLEASE_INSERT_CDROM             "请插入第一张光盘"
#define     TEXTMSG_WINDOW_NAME                     "海之乐章"
#define     TEXTMSG_GAME_VERSION                    "海之乐章α版"  //αβγδε
//
#define     TEXTMSG_JOIN_GAME_OK                    "加入游戏成功。"
#define     TEXTMSG_JOIN_GAME_ERROR_NAME_DUPLICATE  "加入游戏失败：已经存在同名人物。"
#define     TEXTMSG_JOIN_GAME_ERROR_PLAYER_FULL     "加入游戏失败：这个世界已经容纳不下更多的人了。"
#define     TEXTMSG_DISCONNECT_WITH_SERVER          "您与服务器的联机断开了。"
#define     TEXTMSG_WAIT_FOR_LOADING                "正在加载数据中，请等候..."
#define     TEXTMSG_CREATE_PLAYER                   "%s 加入了游戏世界。"
#define     TEXTMSG_DESTROY_PLAYER                  "%s 离开了游戏世界。"
#define     TEXTMSG_WELCOME_JOIN                    "欢迎你来到这个世界。"
#define     TEXTMSG_WAIT_FOR_TRANSFER               "请等候..."
//
#define     TEXTMSG_NAME_ITEM                       "道具"
#define     TEXTMSG_NAME_MAGIC                      "技能"
#define     TEXTMSG_NAME_RACE                       "种族"
#define     TEXTMSG_NAME_COUNTRY                    "国家"
#define     TEXTMSG_NAME_ORGANIZE                   "组织"
#define     TEXTMSG_NAME_TITLE                      "头衔"
#define     TEXTMSG_NAME_SEX                        "性别"
#define     TEXTMSG_NAME_HP                         "生命"
#define     TEXTMSG_NAME_MP                         "内力"
#define     TEXTMSG_NAME_ATT                        "攻击力"
#define     TEXTMSG_NAME_DP                         "防御力"
#define     TEXTMSG_NAME_XFIRE                      "火系防御系数"
#define     TEXTMSG_NAME_XWATER                     "水系防御系数"
#define     TEXTMSG_NAME_XDUST                      "土系防御系数"
#define     TEXTMSG_NAME_XAIR                       "空气防御系数"
#define     TEXTMSG_NAME_DEXT                       "敏捷度"
#define     TEXTMSG_NAME_MOVE_SPEED                 "移动速度"
#define     TEXTMSG_NAME_EYESHOT                    "视野半径"
#define     TEXTMSG_NAME_WIT                        "智力"
#define     TEXTMSG_NAME_STRENGTH                   "力量"
#define     TEXTMSG_NAME_RESP                       "反应力"
#define     TEXTMSG_NAME_VIM                        "活力"
#define     TEXTMSG_NAME_SPIRIT                     "精力"
#define     TEXTMSG_NAME_EXP                        "经验值"
#define     TEXTMSG_NAME_LEVEL                      "等级"
#define     TEXTMSG_NAME_SHIPSPEED                  "航速"
#define     TEXTMSG_NAME_WINDDIR                    "风向"
#define     TEXTMSG_NAME_WEATHER                    "天气"
//
#define     TEXTMSG_NOT_ENOUGH_BAG_SPACE            "没有足够的存放空间。"
#define     TEXTMSG_NOT_ENOUGH_MAP_SPACE            "附近已经容纳不下新的东西了。"
#define     TEXTMSG_NOT_ENOUGH_MONEY                "没有足够的金钱。"
#define     TEXTMSG_NOT_ENOUGH_MP                   "没有足够的法力。"
#define     TEXTMSG_CAN_NOT_USE_MAGIC_IN_TOWN       "技能在城镇里不能使用。"
#define     TEXTMSG_LEVEL_UPGRADE                   "等级升高了"
//
#define     TEXTMSG_ABNORMITY_FUNK                  "恐惧"
#define     TEXTMSG_ABNORMITY_FRENZY                "狂暴"
#define     TEXTMSG_ABNORMITY_WEEK                  "虚弱"
#define     TEXTMSG_ABNORMITY_CRAZY                 "疯狂"
#define     TEXTMSG_ABNORMITY_ANGRY                 "愤怒"
#define     TEXTMSG_ABNORMITY_VIRUS                 "中毒"
#define     TEXTMSG_ABNORMITY_NUMB                  "麻痹"
#define     TEXTMSG_ABNORMITY_COSTIVE               "减速"
#define     TEXTMSG_ABNORMITY_NIMBLE                "加速"
//
#define     TEXTMSG_ADD_STATUS                      "使出现异常"
#define     TEXTMSG_DEL_STATUS                      "解除异常"
//
#define     TEXTMSG_BUY_COST                        "买入价格"
#define     TEXTMSG_SELL_VALUE                      "卖出价格"
#define     TEXTMSG_ADD_STRENGTH                    "力量"
#define     TEXTMSG_ADD_RESP                        "反应力"
#define     TEXTMSG_ADD_VIM                         "活力"
#define     TEXTMSG_ADD_SPIR                        "精力"
#define     TEXTMSG_ADD_HP                          "生命力"
#define     TEXTMSG_ADD_MAX_HP                      "最大生命力"
#define     TEXTMSG_ADD_MP                          "法力"
#define     TEXTMSG_ADD_MAX_MP                      "最大法力"
#define     TEXTMSG_ADD_ATT                         "攻击力"
#define     TEXTMSG_ADD_DP                          "防御力"
#define     TEXTMSG_ADD_XFIRE                       "火系防御系数"
#define     TEXTMSG_ADD_XWATER                      "水系防御系数"
#define     TEXTMSG_ADD_XDUST                       "土系防御系数"
#define     TEXTMSG_ADD_XAIR                        "空气系防御系数"
#define     TEXTMSG_ADD_DEXT                        "敏捷度"
#define     TEXTMSG_ADD_WIT                         "智力"
#define     TEXTMSG_ADD_ATTACK_SPEED                "攻击速度"
#define     TEXTMSG_ADD_MOVE_SPEED                  "移动速度"
#define     TEXTMSG_ADD_EYESHOT                     "视野半径"
#define     TEXTMSG_ADD_HP_RESTORE                  "生命力回复速度"
#define     TEXTMSG_ADD_MP_RESTORE                  "内力回复速度"
//
#define     TEXTMSG_YOU_ENDED_ALLY_WITH_OTHER       "您终止了和~C4%s~C0的联盟。"
#define     TEXTMSG_OTHER_ENDED_ALLY_WITH_YOU       "~C4%s~C0终止了和您的联盟。"
#define     TEXTMSG_YOU_CANCELED_ALLY_REQUEST       "您取消了希望和~C4%s~C0联盟的请求。"
#define     TEXTMSG_OTHER_CANCLED_ALLY_REQUEST      "~C4%s~C0取消了希望和您联盟的请求。"
#define     TEXTMSG_YOU_HAVE_ALLIED_WITH_OTHER      "您已经成功的和~C4%s~C0联盟了。"
#define     TEXTMSG_HAVE_SEND_ALLY_REQUEST          "已经向~C4%s~C0发出了联盟请求，请等待回复。"
#define     TEXTMSG_HAVE_RECEIVED_ALLY_REQUEST      "~C4%s~C0向您发出了联盟请求。"
#define     TEXTMSG_NEUTRAL_WITH_OTHER              "您现在和~C4%s~C0保持中立。"
#define     TEXTMSG_NEUTRAL_WITH_YOU                "~C4%s~C0现在和您保持中立。"
#define     TEXTMSG_OPPOSE_WITH_OTHER               "您现在和~C4%s~C0是敌对的了。"
#define     TEXTMSG_OPPOSE_WITH_YOU                 "~C4%s~C0现在和您是敌对的了。"
//
#define     TEXTMSG_HAVE_RECEIVED_TASK              "接下了新任务。"
#define     TEXTMSG_HAVE_FINISHED_TASK              "任务完成了。"
#define     TEXTMSG_HAVE_CANCELED_TASK              "任务取消了。"
//
#define     TEXTMSG_SOMEONE_IS_BUSY                 "%s 正忙着呢"
//
#define     TEXTMSG_GET_EXP                         "获得了经验值 %d。"
#define     TEXTMSG_GET_MONEY                       "获得了金币 %d。"
#define     TEXTMSG_GET_SKILL_POINT                 "获得技术点 %d。"
#define     TEXTMSG_GET_SOMETHING                   "获得了 %s。"
#define     TEXTMSG_USE_SOMETHING                   "使用了物品 %s。"
#define     TEXTMSG_USE_MONEY                       "使用了金币 %d。"
#define     TEXTMSG_JOIN_ORGANIZE                   "您加入了 %s。"
#define     TEXTMSG_SECEDE_ORGANIZE                 "您退出了 %s。"
//
#define     TEXTMSG_ENUM_PLAYER_KILL_NPC            "%s 杀死怪物 %d 只。"
#define     TEXTMSG_ENUM_PLAYER_CRYSTAL             "%s 拥有水晶 %d 颗。"
#define     TEXTMSG_ENUM_PLAYER_WHERE               "%s 现在处在 %s 的 %s。"
#define     TEXTMSG_ENUM_PLAYER_LEVEL               "%s 现在的等级是 %d。"
#define     TEXTMSG_ENUM_PLAYER_CASH                "%s 现在拥有金钱 %d。"
#define     TEXTMSG_ENUM_RELATION_ALLY              "%s 与 %s 的关系是联盟。"
#define     TEXTMSG_ENUM_RELATION_OPPOSE            "%s 与 %s 的关系是敌对。"
#define     TEXTMSG_ENUM_RELATION_NEUTRAL           "%s 与 %s 的关系是中立。"
#define     TEXTMSG_ENUM_PLAYER_NAME                "玩家 %s。"
#define     TEXTMSG_ONLY_YOU_IN_THE_WORLD           "目前这个世界只有一个玩家 %s。"
//
#define     TEXTMSG_ASK_SURE_DELETE_CHAR            "您确定需要删除人物%s吗？"
#define     TEXTMSG_YES_DELETE_CHAR                 "删除"
#define     TEXTMSG_NO_DELETE_CHAR                  "取消"
#define     TEXTMSG_EXIST_SAME_NAME_SAVE_CHAR       "已经存在同名的人物，请重新命名。"
//
#define     TEXTMSG_MENU_MINIMIZE                   "最小化"
#define     TEXTMSG_MENU_MINIMIZE_INFO              "~C0最小化~C0"
#define     TEXTMSG_MENU_MAXIMIZE                   "最大化"
#define     TEXTMSG_MENU_MAXIMIZE_INFO              "~C0最大化~C0"
#define     TEXTMSG_MENU_CLOSE                      "关闭"
#define     TEXTMSG_MENU_CLOSE_INFO                 "~C0关闭~C0"
//
#define     TEXTMSG_MENU_STATE                      "状态(C)"
#define     TEXTMSG_MENU_STATE_INFO                 "~C0状态(~C4C~C0)~C0"
#define     TEXTMSG_MENU_ITEM                       "装备(I)"
#define     TEXTMSG_MENU_ITEM_INFO                  "~C0装备(~C4I~C0)~C0"
#define     TEXTMSG_MENU_MAGIC                      "技能(T)"
#define     TEXTMSG_MENU_MAGIC_INFO                 "~C0技能(~C4T~C0)~C0"
#define     TEXTMSG_MENU_TASK                       "任务(Q)"
#define     TEXTMSG_MENU_TASK_INFO                  "~C0任务(~C4Q~C0)~C0"
#define     TEXTMSG_MENU_SHIP                       "船只(S)"
#define     TEXTMSG_MENU_SHIP_INFO                  "~C0船只(~C4S~C0)~C0"
#define     TEXTMSG_MENU_HP                         "HP %d / %d"
#define     TEXTMSG_MENU_MP                         "MP %d / %d"
#define     TEXTMSG_MENU_ADDRESS_BOOK               "通讯簿(M)"
#define     TEXTMSG_MENU_ADDRESS_BOOK_INFO          "~C0通讯簿(~C4M~C0)~C0"
#define     TEXTMSG_MENU_CHAT_RECORD                "对话记录(H)"
#define     TEXTMSG_MENU_CHAT_RECORD_INFO           "~C0对话记录(~C4H~C0)~C0"
#define     TEXTMSG_MENU_CHAT_INPUT                 "输入文字(Enter)"
#define     TEXTMSG_MENU_CHAT_INPUT_INFO            "~C0输入文字(~C4Enter~C0)~C0"
//
#define     TEXTMSG_UIITEM_DROP_GOLD                "丢下金钱"
//
#define     TEXTMSG_INVALID_SAVE_VERSION            "存档版本错误"
#define     TEXTMSG_INVALID_CHECKSUM                "数据错误"
//
#define     TEXTMSG_NEED_MP                         "消耗MP:"
//
#define     TEXTMSG_UISETUP_ALLY                    "联盟"
#define     TEXTMSG_UISETUP_OPPOSE                  "敌对"
#define     TEXTMSG_UISETUP_CHAT_AUDIBLE            "传送信息"
#define     TEXTMSG_UISETUP_CHAT_FORBID             "屏蔽信息"
//
#define     TEXTMSG_PREV_PAGE                       "上一页"
#define     TEXTMSG_NEXT_PAGE                       "下一页"
//
#define     TEXTMSG_ADD_BASE_STRENGTH               "增加基本力量"
#define     TEXTMSG_SUB_BASE_STRENGTH               "减少基本力量"
#define     TEXTMSG_ADD_BASE_INSTINCT               "增加基本直觉"
#define     TEXTMSG_SUB_BASE_INSTINCT               "减少基本直觉"
#define     TEXTMSG_ADD_BASE_WIT                    "增加基本智力"
#define     TEXTMSG_SUB_BASE_WIT                    "减少基本智力"
#define     TEXTMSG_ADD_BASE_LUCK                   "增加基本运气"
#define     TEXTMSG_SUB_BASE_LUCK                   "减少基本运气"
//
#define     TEXTMSG_CREDIT_CARD                     "信用卡"
#define     TEXTMSG_POINTS_CARD                     "时数卡"
#define     TEXTMSG_IME_QUANJIAO                    "全角"
#define     TEXTMSG_IME_BANJIAO                     "半角"
#define     TEXTMSG_IME_CHINESE_PUNCTUATION         "中文标点"
#define     TEXTMSG_IME_ENGLISH_PUNCTUATION         "英文标点"
//
#define     TEXTMSG_SERVER_ACTIVE                   "启动"
#define     TEXTMSG_SERVER_MAINTAIN                 "维护中"
#define     TEXTMSG_COUNTRY_NAME_CHINA              "中国"
#define     TEXTMSG_COUNTRY_NAME_ENGLAND            "英国"
#define     TEXTMSG_COUNTRY_NAME_SWEDEN             "瑞典"
#define     TEXTMSG_COUNTRY_NAME_FRANCE             "法国"
#define     TEXTMSG_COUNTRY_NAME_GERMANY            "德国"
#define     TEXTMSG_COUNTRY_NAME_SPAIN              "西班牙"
#define     TEXTMSG_COUNTRY_NAME_PORTUGAL           "葡萄牙"
#define     TEXTMSG_COUNTRY_NAME_ITALY              "义大利"
#define     TEXTMSG_COUNTRY_NAME_DENMRKE            "丹麦"
#define     TEXTMSG_COUNTRY_NAME_FINLAND            "芬兰"
#define     TEXTMSG_COUNTRY_NAME_GREECE             "希腊"
#define     TEXTMSG_COUNTRY_NAME_NORWAY             "挪威"
#define     TEXTMSG_COUNTRY_NAME_IRELAND            "爱尔兰"
#define     TEXTMSG_COUNTRY_NAME_TUNIS              "突尼斯"
#define     TEXTMSG_COUNTRY_NAME_ARAB               "阿拉伯"
#define     TEXTMSG_COUNTRY_NAME_TURKEY             "土耳其"
#define     TEXTMSG_COUNTRY_NAME_AFRICA             "非洲"
#define     TEXTMSG_COUNTRY_NAME_KOREA              "韩国"
#define     TEXTMSG_COUNTRY_NAME_JAPAN              "日本"
#define     TEXTMSG_COUNTRY_NAME_INDIA              "印度"
#define     TEXTMSG_COUNTRY_NAME_DUMMY              "无"

#define     TEXTMSG_CAREER_NAME_GENERAL             "提督"
#define     TEXTMSG_CAREER_NAME_SWORDER             "剑士"
#define     TEXTMSG_CAREER_NAME_THIEF               "小偷"
#define     TEXTMSG_CAREER_NAME_TRADER              "商人"
#define     TEXTMSG_CAREER_NAME_EXPLORER            "探险家"
#define     TEXTMSG_CAREER_NAME_CLERIC              "牧师"
#define     TEXTMSG_CAREER_NAME_HOROSCOPER          "占星术士"
#define     TEXTMSG_CAREER_NAME_DUMMY               "无"

#define     TEXTMSG_SEX_NAME_MALE                   "男"
#define     TEXTMSG_SEX_NAME_FEMALE                 "女"
#define     TEXTMSG_SEX_NAME_DUMMY                  "无"

#define     TEXTMSG_WEATHER_TYPE_NAME_WIND          "风"
#define     TEXTMSG_WEATHER_TYPE_NAME_FINE          "晴"
#define     TEXTMSG_WEATHER_TYPE_NAME_RAIN          "雨"
#define     TEXTMSG_WEATHER_TYPE_NAME_THUNDER       "雷"
#define     TEXTMSG_WEATHER_TYPE_NAME_FOG           "雾"
#define     TEXTMSG_WEATHER_TYPE_DUMMY              "??"

#define     TEXTMSG_CHAT_CHEER_GAOXING              "高兴"
#define     TEXTMSG_CHAT_ANGRY_QIFEN                "气愤"
#define     TEXTMSG_CHAT_BECKON_NIHAO               "你好"
#define     TEXTMSG_CHAT_BECKON_ZHAOSHOU            "招手"
#define     TEXTMSG_CHAT_BECKON_ZAIJIAN             "再见"
#define     TEXTMSG_CHAT_COURT_QIUAI                "求爱"
#define     TEXTMSG_CHAT_FAINT_YUNDAO               "晕倒"
#define     TEXTMSG_CHAT_SAY_NO_BU                  "不"
#define     TEXTMSG_CHAT_BOW_JUGONG                 "鞠躬"
#define     TEXTMSG_CHAT_WIN_SHENGLI                "胜利"
#define     TEXTMSG_CHAT_SWASH_XIAHU                "吓唬"
#define     TEXTMSG_CHAT_XXPOWER_XULI               "蓄力"
#define     TEXTMSG_CHAT_XXBEATED_SHOUSHANG         "受伤"

#define		TEXTMSG_ASK_BUY_ITEM					"Name:%s\nPrice%d\nAre you sure ?"
#define		TEXTMSG_ASK_DEL_CHARACTER				"Delete character:%s\nAre you sure ?"

//--------------------------
#define     GAMEMSG_PLAYER_JOIN                     "%s JOIN"
#define     GAMEMSG_PLAYER_EXIT                     "%s EXIT"
#define     GAMEMSG_PLAYER_FIGHT_ENABLED            "YOU CHANED TO FIGHT"
#define     GAMEMSG_PLAYER_FIGHT_DISABLED           "YOU CHANED TO NORMAL"
#define     GAMEMSG_ENTER_ZONE                      "YOU ENTERED %s"

#define		TEXTMSG_BANK_LOAD_MONEY					"How many money load ?"
#define		TEXTMSG_BANK_SAVE_MONEY					"How many money save ?"

#endif//GB_VERSION    } 
//----------------------------------------------------------------------------------------------------------


void    errormsg_file_open(char *filename);
void    errormsg_memory(void);
//
void    display_error_message(USTR *message, SLONG flag, void *vbitmap);
void	display_message(char *title, char *text, DWORD type, DWORD time, DWORD font_size);
void    log_encrypt_message(int p, char *strMsg, ...);
//


#endif//_ERRORMSG_H_
